### PR TITLE
WIP: Master with console

### PR DESCRIPTION
**Pull request by raha1923**
API Console implemented and fully configured to works fine on Redoc.

The base of API console feature implemented [here](https://github.com/nutanix/ReDoc)

Notice: Please do not merge.

### CODE REVIEW

**Comment by raha1923** [comment]
@nutanix

**Comment by NurFaizin** [comment]
Hi @raha1923 , many thanks for your works.
Let me ask something, why when I bundle the library it doesn't show the try button? But when I start the demo it runs well.

**Comment by raha1923** [comment]
> Hi @raha1923 , many thanks for your works.
> Let me ask something, why when I bundle the library it doesn't show the try button? But when I start the demo it runs well.

Hi
Well I can't give a solution right now, but I will give it to you next weak. I think it's not a big deal because I remember I've done it before easily. Just I'm busy and out of context right now :)))

**Comment by raha1923** [comment]
The built-in console is ready to use. please read the readme to find out how to enable the console.

**Comment by mxl456** [comment]
Hi Raha, amazing work! I am trying to use your fork. But i don't know what would be the easiest way to do that. Do you have CDN version? i don't know how to install your module. Thanks!

**Comment by lsalazarm99** [comment]
Hi. Many thanks for implementing this feature.

I'm trying to use it. I downloaded your code, executed `bundle:standalone` and it generated the `standalone.js` file. But there are 2 issues:
- The console is enabled, but there is no way to introduce parameters.

**Expected:**
image

**Result:**
image

- It shows an error in the console: `GET http://URL/083be6893a55a3555bcd.worker.js 404 (Not Found)`. I can't get the file from the bundle folder, there is only its map file.

Is it supposed to work that way?

**Comment by raha1923** [comment]
hi @lsalazarm99 
Thank you so much. Well a new update is on the way and it contains a big bunch of changes, we've solved the problem about sending GET requests. Please just watch the fork to get the new changes and find this tool useful and ready/easy to use.

**Comment by kamaydeo** [comment]
@raha1923 When can we expect a new update? I am looking forward to use it as soon as it is available.

**Comment by kamaydeo** [comment]
By the way, when I run npm run bundle:standalone I get following error.

```
ERROR in /tools/redoc-api-console/cli/index.ts
[tsl] ERROR in /tools/redoc-api-console/cli/index.ts(270,67)
      TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'typeof Redoc' is not assignable to parameter of type 'string | FunctionComponent<{ store: AppStore; }> | ComponentClass<{ store: AppStore; }, any>'.
      Type 'typeof Redoc' is not assignable to type 'ComponentClass<{ store: AppStore; }, any>'.
        Type 'Redoc' is missing the following properties from type 'Component<{ store: AppStore; }, any, any>': context, setState, forceUpdate, props, and 2 more.

ERROR in /tools/redoc-api-console/src/common-elements/SwitchBox.tsx
[tsl] ERROR in /tools/redoc-api-console/src/common-elements/SwitchBox.tsx(5,26)
      TS2615: Type of property 'defaultProps' circularly references itself in mapped type 'Pick<ForwardRefExoticComponent<Pick<Pick<any, Exclude<keyof ReactDefaultizedProps<StyledComponentInnerComponent<WithC>, ComponentPropsWithRef<StyledComponentInnerComponent<WithC>>>, StyledComponentInnerAttrs<...> | ... 1 more ... | StyledComponentInnerAttrs<...>> | Exclude<...> | Exclude<...> | Exclude<...>> & Parti...'.

ERROR in /tools/redoc-api-console/src/common-elements/SwitchBox.tsx
[tsl] ERROR in /tools/redoc-api-console/src/common-elements/SwitchBox.tsx(5,26)
      TS2615: Type of property 'defaultProps' circularly references itself in mapped type 'Pick<ForwardRefExoticComponent<Pick<Pick<any, Exclude<keyof ReactDefaultizedProps<StyledComponentInnerComponent<WithC>, ComponentPropsWithRef<StyledComponentInnerComponent<WithC>>>, any>> & Partial<...>, any> & { ...; } & WithChildrenIfReactComponentClass<...>>, "defaultProps" | ... 2 more ... | "$$typeof">'.

ERROR in /tools/redoc-api-console/src/common-elements/dropdown.ts
[tsl] ERROR in /tools/redoc-api-console/src/common-elements/dropdown.ts(12,38)
      TS2769: No overload matches this call.
  Overload 1 of 2, '(component: AnyStyledComponent): ThemedStyledFunction<any, ResolvedThemeInterface, any, any>', gave the following error.
    Argument of type 'typeof ReactDropdown' is not assignable to parameter of type 'AnyStyledComponent'.
      Type 'typeof ReactDropdown' is not assignable to type 'StyledComponent<any, any, any, never>'.
        Type 'typeof ReactDropdown' is not assignable to type 'string'.
  Overload 2 of 2, '(component: "symbol" | "object" | "template" | "title" | "input" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | ... 157 more ... | ComponentClass<...>): ThemedStyledFunction<...>', gave the following error.
    Argument of type 'typeof ReactDropdown' is not assignable to parameter of type '"symbol" | "object" | "template" | "title" | "input" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | ... 157 more ... | ComponentClass<...>'.
      Type 'typeof ReactDropdown' is not assignable to type 'ComponentClass<any, any>'.
        Type 'ReactDropdown' is missing the following properties from type 'Component<any, any, any>': context, setState, forceUpdate, render, and 3 more.
Child worker:
     2 assets
    Entrypoint main = c5bb51fdb9cd0d94fab7.worker.js c5bb51fdb9cd0d94fab7.worker.js.map
    [59] (webpack)/buildin/global.js 472 bytes {0} [built]
    [97] ./node_modules/workerize-loader/dist/rpc-worker-loader.js!./node_modules/ts-loader??ref--4-0!./node_modules/babel-loader/lib??ref--4-1!./src/services/SearchWorker.worker.ts + 1 modules 13.8 KiB {0} [built]
         | ./node_modules/workerize-loader/dist/rpc-worker-loader.js!./node_modules/ts-loader??ref--4-0!./node_modules/babel-loader/lib??ref--4-1!./src/services/SearchWorker.worker.ts 3.78 KiB [built]
         |     + 1 hidden module
        + 96 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! redoc@2.0.0-rc.23 bundle:standalone: `webpack --env.standalone --mode=production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the redoc@2.0.0-rc.23 bundle:standalone script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-06-12T03_05_42_211Z-debug.log```

I am using npm v6.14.4 and node v14.3.0

**Comment by wll8** [comment]
- [👉 View video](https://cdn.jsdelivr.net/gh/wll8/static/Video_20200518145834_redoc_show.mp4)
- [👉 online preview](https://wll8.github.io/redoc-try/index.html)

Add `Try it out` function like [swagger](https://petstore.swagger.io/) on [redoc](https://github.com/Redocly/redoc).

re-doc try

**Comment by rubenzup** [comment]
Im trying to build your version of Redoc but is getting too many error in TypeScript , it would be good if you make a separate npm package, or a standalone.js, Im trying to use in a Next.js project, and cant do it

**Pull request merged**
